config/routes.rb
# Rails.application.routes.draw do
#   # scope "(:locale)", locale: "/#{I18n.available_locales.join("|")}/" do
#   #   resources :blog_post
#   #   root "blog_posts#index"
#   # end

#   devise_for :users, controllers: { registrations: 'users/registrations' }
  
#   get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
#   post "/blog_posts", to: "blog_posts#create", as: :blog_posts

#   get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
#   patch "/blog_posts/:id", to: "blog_posts#update"
#   delete "/blog_posts/:id", to: "blog_posts#destroy"
  
#   get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post

#   post "blog_posts/:id/comments", to: "comments#create", as: :comments

#   # Defines the root path route ("/")
#   root "blog_posts#index"
  
# end



# Rails.application.routes.draw do

#   devise_for :users, controllers: { registrations: 'users/registrations' }
  
#   resources :blog_posts do
#     resources :comments, only: [ :create, :destroy ], as: :blog_post_comments
#   end

#   # Defines the root path route ("/")
#   root "blog_posts#index"

# end

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root "blog_posts#index"
  
  resources :blog_posts do 
    resources :comments, only: [:create, :destroy]
  end
  
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  
  paginates_per 3

  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]
  before_action :is_blog_post_owner, only: [:edit, :update]

  def index
    @blog_posts = BlogPost.order(updated_at: :desc).page params[:page]
  end

  def show
    @comments = Comment.where(blog_post_id: params[:id])
    @comment = Comment.new
    @last_posts = BlogPost.last(3)
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = current_user.blog_posts.build(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound 
    redirect_to root_path
  end

  def is_blog_post_owner
    if current_user != @blog_post.user
      redirect_to @blog_post
    end
  end

end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post, class: "form-container" do |form| %>

  <% if form.object.errors.any? %>
    <div class="form-error-container">
      <% form.object.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"> <%= message %> </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-item-wrapper mb-4">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-rich_item-wrapper mb-4">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <%= form.button "Submit", class: "btn btn-primary btn-block mb-4" %>
  
<% end %>

app/views/blog_posts/edit.html.erb
<h1 class="mb-5" >Edit post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>

<%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "form-button delete" %>

app/views/blog_posts/index.html.erb
<div class="container my-5">

  <div class="row flex d-flex gap-4">

    <% @blog_posts.each do |blog_post| %>

      <div class="">
        <div class="card h-100">

          <div class="card-body">

            <h2 class="card-title"><%= link_to blog_post.title, blog_post %></h2>

            <p class="card-text"><%= truncate(blog_post.content.to_plain_text, length: 200) %></p>

          </div>

          <div class="card-footer text-muted d-flex justify-content-between align-items-center">
            <div class="date-name">
              <%= l(blog_post.created_at, format: :long) %>
              <p><%= blog_post.user.name %></p>
            </div>
            <%= link_to "Read more", blog_post, class: "btn btn-primary" %>
          </div>

        </div>
      </div>

    <% end %>

  </div>

  <%= paginate @blog_posts, previous_label: "Previous", next_label: "Next", class: "pagination justify-content-center" %>

</div>

app/views/blog_posts/new.html.erb
<h1>New post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-8">
      <div class="card mb-3">

        <div class="card-body">
          <h1 class="card-title"><%= @blog_post.title%></h1>
          <p class="card-text"><%= @blog_post.content %></p>
        </div>

      </div>

      <% if current_user == @blog_post.user %>
        <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-primary mb-3" %>
      <% end %>

      <section>

        <h2 class="mb-3">Comments</h2>

        <% @blog_post.comments.each do |comment| %>
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-subtitle mb-2 text-muted">

                <% if comment.user %>
                  <%= comment.user.name %>
                <% else %>
                  <%= "Anonimous" %>
                <% end %>

              </h5>
              <p class="card-text"><%= comment.content %></p>
              <small class="card-text text-muted"><%= comment.created_at.strftime("%B %d, %Y") %></small>
            </div>
          </div>
        <% end %>

        <h2 class="mb-3">Add a comment</h2>

        <%= form_for [@blog_post, @blog_post.comments.build], class: "mt-3" do |f| %>
          <div class="form-group">
            <%= f.text_field :content, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>

      </section>
    </div>

    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Recent Posts</h5>
          <% @last_posts.each do |blog_post| %>
            <h6 class="card-subtitle mb-2"><%= link_to blog_post.title, blog_post %></h6>
            <small class="card-text text-muted"><%= blog_post.created_at.strftime("%B %d, %Y") %></small>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>