config/routes.rb
# Rails.application.routes.draw do
#   # scope "(:locale)", locale: "/#{I18n.available_locales.join("|")}/" do
#   #   resources :blog_post
#   #   root "blog_posts#index"
#   # end

#   devise_for :users, controllers: { registrations: 'users/registrations' }
  
#   get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
#   post "/blog_posts", to: "blog_posts#create", as: :blog_posts

#   get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
#   patch "/blog_posts/:id", to: "blog_posts#update"
#   delete "/blog_posts/:id", to: "blog_posts#destroy"
  
#   get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post

#   post "blog_posts/:id/comments", to: "comments#create", as: :comments

#   # Defines the root path route ("/")
#   root "blog_posts#index"
  
# end



# Rails.application.routes.draw do

#   devise_for :users, controllers: { registrations: 'users/registrations' }
  
#   resources :blog_posts do
#     resources :comments, only: [ :create, :destroy ], as: :blog_post_comments
#   end

#   # Defines the root path route ("/")
#   root "blog_posts#index"

# end

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root "blog_posts#index"
  
  resources :blog_posts do 
    resources :comments, only: [:create, :destroy]
  end
  
end

app/views/shared/_navbar.html.erb

  <nav class="navbar navbar-expand-lg">
  <div class="container-fluid">

    <%= link_to "Blog Mainô", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto gap-4">

        <li class="nav-item">
          <%= link_to "New post", new_blog_post_path, class: "nav-link" %>
        </li>
        
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>